### ISSUE TITLE
When using the first item in the list as a placeholder (value="" and disabled) the selected attribute is not applied for the item inside the text-field

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-dropdown-menu#103]
```html
<vaadin-dropdown-menu>
  <template>
    <vaadin-list-box>
      <vaadin-item value="" disabled>
        Select an option<br>
        <small>Pretty please</small>
      </vaadin-item>
      <hr>
      <vaadin-item value="1">
        Option one<br>
        <small>Item description</small>
      </vaadin-item>
      <vaadin-item value="2">
        Option two<br>
        <small>Item description</small>
      </vaadin-item>
      <vaadin-item value="3">
        Option three<br>
        <small>Item description</small>
      </vaadin-item>
      <vaadin-item value="4">
        Option four<br>
        <small>Item description</small>
      </vaadin-item>
    </vaadin-list-box>
  </template>
</vaadin-dropdown-menu>
```

Expected result:
![screen shot 2018-02-23 at 15 38 14](https://user-images.githubusercontent.com/66382/36596805-9a9d8522-18af-11e8-8962-f799ab8267e0.png)

Actual result:
![screen shot 2018-02-23 at 15 37 58](https://user-images.githubusercontent.com/66382/36596811-a0882172-18af-11e8-85ad-95d824b4d811.png)

The `vaadin-item` which is shown inside the `vaadin-dropdown-menu-text-field` does not get the `selected`, so the style adjustments, which remove the horizontal padding from the item, are not applied.

**Comment by web-padawan** [comment]
The reason is this code: https://github.com/vaadin/vaadin-item/blob/master/src/vaadin-item-mixin.html#L113

So, when we clone selected item, it has the `selected` attribute, but once we attach it to the `value` slot, it loses it because of the property observer fired.

We can workaround this explicitly in `vaadin-dropdown-menu` by moving [this line](https://github.com/vaadin/vaadin-dropdown-menu/blob/master/src/vaadin-dropdown-menu.html#L501) down and always invoking it after we append item to the slot.

**Comment by jouni** [comment]
I was also wondering if the way Lumo adjusts the styles of the selected item, [using the `[selected]` selector](https://github.com/vaadin/vaadin-dropdown-menu/blob/master/theme/lumo/vaadin-dropdown-menu.html#L21-L24), is a good practice.

**Comment by jouni** [comment]
Haven’t figured out a better system either, to get the required visual results.
