### ISSUE TITLE
Clean up demos

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-dropdown-menu#20]
Remove:
<img width="862" alt="screenshot 2017-11-01 06 41 13" src="https://user-images.githubusercontent.com/1222264/32260311-b207f4b6-becf-11e7-8e81-f885c725daab.png">

Don't use `http://www.sciencekids.co.nz` resources in the demos (the flags). Use emoji for example.

**Comment by manolo** [comment]
I already thought on this when adding the demo, so images are intentional to demonstrate that we could use any arbitrary html content as selected item but the selected value is the text content. Actually they are flags but in my first version was pictures of faces.

So if I add flags as part of the texContent like `<vaadin-item>🇪🇸 Spain</vaadin-item>` final `dropdown.value == "🇪🇸 Spain"` 

One solution could be the following, but needs to set labels which is something that I wanted to avoid at the beginning.  

```
 <vaadin-item label="Spain">
  <span style="margin-right: 10px">🇪🇸 </span> Spain
 </vaadin-item>
```

We already depend on external images in other components demos

**Comment by manolo** [comment]
About the noise in `index.html` was fixed in https://github.com/vaadin/vaadin-dropdown-menu/commit/b95f8d0bdf5bfab8149faaf3fb03ea517591341a

**Comment by tomivirkki** [comment]
Use the label, that's what it's for.

**Comment by manolo** [comment]
`label` was already demoed in another demo. Leaving images so as the user can focuses in  the feature we want to demonstrate. Images now are aligned with the used in other examples
