### ISSUE TITLE
Doesn't open on Firefox by clicking the input

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-dropdown-menu#38]
When there's no pre-selected value in the dropdown menu, the overlay doesn't open by clicking the contained `vaadin-text-field`

**Comment by web-padawan** [comment]
The reason is that Firefox doesn't propagate click event on disabled form items.

It can be fixed by setting `pointer-events: none` on the native input, but that makes it hard to test.
I have tried all of these options:
- `MockInteractions.tap` (which checks for this CSS rule and simply returns)
- calling `nativeInput.dispatchEvent(new MouseEvent('click', {bubbles: true}))`
- calling 'nativeInput.click()'

@manolo do you have any ideas on how to test it properly, or maybe another suggestion to fix?

**Comment by web-padawan** [comment]
UPD: using `document.elementFromPoint` does the trick for me.
