### ISSUE TITLE
Consider setting the width of the overlay to equal input width

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-dropdown-menu#97]
Should we set the width of the overlay to equal width of the input field?

**Comment by jouni** [comment]
Instead of fixing the width of the overlay to a specific value, set a CSS custom property instead. 

E.g. `<vaadin-dropdown-menu-overlay style="--vaadin-dropdown-menu-width: 123px;">`

This way, the theme developer can decide how to use that information. They can either set it as a fixed `width` or as `min/max-width`.

The same should be done for combo box eventually.

**Comment by jouni** [comment]
I have a fix pending for this in `vaadin-overlay`, so that this can be used in all elements that use vaadin-overlay.
